function ioda_write(S, ncfile)

%
% IODA_WRITE:  Writes IODA observation NetCDF-4 file
%
% ioda_write(S, ncfile)
%
% On Input:
%
%    S       IODA Observations data (struct and cell arrays)
%              (same schema as generated by 'ioda_read')
%
%    ncfile  Output IODA Observations NetCDF-4 filename (string)
%
  
% git $Id$
%=======================================================================%
%  Copyright (c) 2002-2026 The ROMS Group                               %
%    Licensed under a MIT/X style license                               %
%    See License_ROMS.md                            Hernan G. Arango    %
%=======================================================================%
  
disp(['*** Writing IODA observations file:  ', ncfile]);

%------------------------------------------------------------------------
% Write out variables associated with file dimensions.
%------------------------------------------------------------------------

% Write zero values. It only used during JEDI UFO-processing.

ncwrite(ncfile, 'Location', int32(zeros(size(S.longitude))));
ncwrite(ncfile, 'nvars', int32(zeros(size(S.stateID))));
ncwrite(ncfile, 'survey', int32(zeros(size(S.surveyTime))));

%------------------------------------------------------------------------
% Write out 'MetaData' Group variables.
%------------------------------------------------------------------------

ncwrite(ncfile, 'MetaData/dateTime', int64(S.dateTime));

if (isfield(S, 'timeAvgBegin'))
  ncwrite(ncfile, 'MetaData/dateTimeAverageBegin', int64(S.timeAvgBegin));
end

if (isfield(S, 'timeAvgEnd'))
  ncwrite(ncfile, 'MetaData/dateTimeAverageEnd', int64(S.timeAvgEnd));
end

if (isfield(S, 'depth'))
  ncwrite(ncfile, 'MetaData/depth', S.depth);
end

if (isfield(S, 'latitude'))
  ncwrite(ncfile, 'MetaData/latitude', S.latitude);
end

if (isfield(S, 'longitude'))
  ncwrite(ncfile, 'MetaData/longitude', S.longitude);
end
  
if (isfield(S, 'provenance'))
  ncwrite(ncfile, 'MetaData/provenance', S.provenance);
end

if (isfield(S, 'stateID'))
  ncwrite(ncfile, 'MetaData/stateID', int32(S.stateID));
end

if (isfield(S, 'sequenceNumber'))
  ncwrite(ncfile, 'MetaData/sequenceNumber', S.sequenceNumber);
end
  
if (isfield(S, 'areaAvgRadius'))
  ncwrite(ncfile, 'MetaData/spatialAverage', S.areaAvgRadius);
end

if (isfield(S, 'surveyIndex'))
  ncwrite(ncfile, 'MetaData/surveyIndex', int32(S.surveyIndex));
end
  
if (isfield(S, 'surveyIndex'))
  ncwrite(ncfile, 'MetaData/surveyTime', int64(S.surveyTime));
end

if (isfield(S, 'variables_name'))
  ncwrite(ncfile, 'MetaData/variables_name', S.variables_name);
end

if (isfield(S, 'x_grid'))
  ncwrite(ncfile, 'MetaData/x_grid', S.x_grid);
end

if (isfield(S, 'y_grid'))
  ncwrite(ncfile, 'MetaData/y_grid', S.y_grid);
end

if (isfield(S, 'z_grid'))
  ncwrite(ncfile, 'MetaData/z_grid', S.z_grid);
end
  
%------------------------------------------------------------------------
%  Write out other Groups variable(s) data.
%------------------------------------------------------------------------

%  'ObsError' Group.

if (isfield(S, 'ObsError'))
  for i = 1:S.nvars
    Vname = ['ObsError/' S.ncvname{i}];
    ncwrite(ncfile, Vname, S.ObsError{i});
  end
end

%  'ObsValue' Group.

if (isfield(S, 'ObsValue'))
  for i = 1:S.nvars
    Vname = ['ObsValue/' S.ncvname{i}];
    ncwrite(ncfile, Vname, S.ObsValue{i});
  end
end

%  'PreQC' Group.

if (isfield(S, 'PreQC'))
  for i = 1:S.nvars
    Vname = ['PreQC/' S.ncvname{i}];
    ncwrite(ncfile, Vname, int32(S.PreQC{i}));
  end
end

%  'EffectiveError' Group.

if (isfield(S, 'EffectiveError'))
  for i = 1:S.nvars
    Vname = ['EffectiveError/' S.ncvname{i}];
    ncwrite(ncfile, Vname, S.EffectiveError{i});
  end
end

%  'EffectiveQC' Group.

if (isfield(S, 'EffectiveQC'))
  for i = 1:S.nvars
    Vname = ['EffectiveQC/' S.ncvname{i}];
    ncwrite(ncfile, Vname, int32(S.EffectiveError{i}));
  end
end

%  'ObsBias' Group.

if (isfield(S, 'ObsBias'))
  for i = 1:S.nvars
    Vname = ['ObsBias/' S.ncvname{i}];
    ncwrite(ncfile, Vname, S.ObsBias{i});
  end
end

%  'hofx' Group.

if (isfield(S, 'hofx'))
  for i = 1:S.nvars
    Vname = ['hofx/' S.ncvname{i}];
    ncwrite(ncfile, Vname, S.hofx{i});
  end
end

return
